### ISSUE TITLE
Set up landing page

### ISSUE THREAD

**Issue by dcecile** [dcecile/nekusuto#11]
Something for new users to sink their teeth into.
- [x] Use [3 parts](https://github.com/dcecile/nekusuto/files/441108/Messaging_20160825.pdf)
- [x] Clearly state alpha
- [x] Use `<p>Connecting game devs with Let's Player</p>` tagline
- [x] Skip cute, tiny wireframes
- [x] Tweak logo icon
- [x] Check look of a [stock photo](https://unsplash.com/photos/AZMmUy2qL6A)
- [x] Check look of a [motif](https://teamtreehouse.com/)
- [x] Fix up cost copy
- [x] Set up `<head/>`
- [x] Add GitHub link
- [x] Set up domain email address #19 
- [ ] Set up mailing list #12
- [ ] Set up analytics #8 

http://www.black.design/messaging/
https://dodistribute.com/
https://basecamp.com/
https://www.promoterapp.com/
https://teamtreehouse.com/features/organizations
